### ISSUE TITLE
Some problem about training.

### ISSUE THREAD

**Issue by white1-doggy** [burchim/AVEC#14]
I ran into some problems when I was training this code：
![image](https://github.com/burchim/AVEC/assets/76698816/6c461760-7042-42f6-a51e-2bb5aaa55ef3)
And when I debug this problem ,I print the output in model.py in line 255 and try to figure out the reason why loss is nan:
![image](https://github.com/burchim/AVEC/assets/76698816/f6143f60-8984-43a0-8891-71d34df03bc3)
and I get:
![image](https://github.com/burchim/AVEC/assets/76698816/8969a50a-7170-4fe8-acf4-6055dfc63efb)
sometimes the output is normal tensor but most of time is nan.
Can you help me clarify the problem？
Thank you.

**Comment by white1-doggy** [comment]
All the AV,AO,VO training have the same problem.

**Comment by burchim** [comment]
Hi, this looks like the problem that was faced in this [issue](https://github.com/burchim/AVEC/issues/7).

The problem was coming from the fact that the learning rate was given to the optimizer as a tensor and not a float. 
It was fixed using .item() in nnet/optimizer.py (line 74) to convert the lr to float:
`group['lr'] = lr.item()`

Is it working for you?

**Comment by white1-doggy** [comment]
> Hi, this looks like the problem that was faced in this [issue](https://github.com/burchim/AVEC/issues/7).
> 
> The problem was coming from the fact that the learning rate was given to the optimizer as a tensor and not a float. It was fixed using .item() in nnet/optimizer.py (line 74) to convert the lr to float: `group['lr'] = lr.item()`
> 
> Is it working for you?

sorry，It doesn't work, and the loss is still nan,
![image](https://github.com/burchim/AVEC/assets/76698816/68dcc775-e51e-4d81-ac2f-9fc57a54fa0e)
to solve this, I find after the softmax in nnet/attentions.py:311, like:
att_w = att_scores.softmax(dim=-1)
the att_w will become nan, this maybe because nnet/attentions.py:308:
att_scores += (mask.logical_not() * -1e9)
The mask function causes the last dimension to be all -inf, so with softmax, att_w becomes nan. When I do not use mask, the code can run normally and loss will occur normally. However, I think simply removing mask will affect the training results.

**Comment by white1-doggy** [comment]
I also have some environmental issues here. ctcdecode works fine when I use pytorch == 2.0.0, but it appears during training：
![image](https://github.com/burchim/AVEC/assets/76698816/efacc3c7-1093-4a2a-998f-ce32b77d409a)
When I don't use pytorch=2.0.0, the code works fine, but I can't import ctcdecode properly.When I don't use pytorch=2.0.0, the code works fine, but I can't build ctcdecode properly, and when I can build properly, I can't import ctcdecode properly:
![image](https://github.com/burchim/AVEC/assets/76698816/d4cb86ae-90d3-4fc6-948c-e4821299a9e2)
So can you tell me about your environment？Thanks

**Comment by burchim** [comment]
I see, the problem may be related to [this issue](https://github.com/burchim/AVEC/issues/3) then.

The issue was solved by converting the features to float32 during the masking + softmax:
`att_scores = att_scores.float() + (mask.logical_not().float() * -1e9)` [here](https://github.com/burchim/AVEC/blob/ec51ebefc9a488ccf175ab72657eb6a5567bbd04/nnet/attentions.py#L306)
`att_w = att_scores.softmax(dim=-1).type(Q.dtype)` [here](https://github.com/burchim/AVEC/blob/ec51ebefc9a488ccf175ab72657eb6a5567bbd04/nnet/attentions.py#L309)

I will update the code to fix these issues.

**Comment by white1-doggy** [comment]
Thank you for your answer. It is working.

**Comment by white1-doggy** [comment]
你好，我还有一些训练问题需要咨询一下。

当我用 2 A100 80G 时训练AO模型，Batch_size=8，同时训练lrs3和lrs2数据集，就会报错out of memory，并且训练时间会达到5个小时一个epoch。

当只使用ls2数据集，Batch_size=16，num_workers=4时，也会报错out of memory，此时20分钟一个epoch。

当只使用ls2数据集，Batch_size=8，num_workers=4时，此时40分钟一个epoch，但是会出现多个epoch后出现loss=nan的问题。

以上问题都导致我不能正常训练，请问可以详细告诉我，您训练这个模型的时间以及细节设置吗，非常感谢

**Comment by white1-doggy** [comment]
Hi, I still have some training questions to ask.

When I train the AO model at 2 A100 80G, Batch_size=8, and train the lrs3 and lrs2 data sets simultaneously, errors will be reported out of memory and the training time will reach an epoch of 5 hours.

When only the ls2 data set is used, Batch_size=16, num_workers=4, an error will also be reported out of memory. In this case, the epoch is 20 minutes.

When only ls2 data set is used, Batch_size=8, num_workers=4, the epoch is 40 minutes, but loss=nan occurs when multiple epochs are used.

All the above problems have caused me to be unable to train normally. Could you please tell me the time and details of your training of this model in detail? Thank you very much！！
